package pantalla;

//renderizador
import renderizador.Exportar;
import renderizador.ColumnaAmarillaRenderer;
import java.io.IOException;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;

//diseño y archivo pdf
import com.itextpdf.text.Document;
import com.itextpdf.text.Rectangle;
import com.itextpdf.text.pdf.PdfName;
import com.itextpdf.text.pdf.PdfNumber;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfPageEventHelper;
import com.itextpdf.text.pdf.PdfWriter;

//conexion sql
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Conexion.Conexion;


// libreria para buscar
import javax.swing.table.TableRowSorter;
import java.awt.event.KeyEvent;
import java.awt.event.KeyAdapter;

//libreria pdf txt etc
import java.io.BufferedWriter;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import javax.swing.RowFilter;
import javax.swing.JFileChooser;
import renderizador.AnimacionBorderPanel1;

/**
 *
 * @author abel
 */
public class datospersonales extends javax.swing.JPanel {

    Exportar obj;

    Conexion con2 = new Conexion();
    Connection conet;
    DefaultTableModel modelo;
    Statement st;
    ResultSet rs;
    int idc;

    private TableRowSorter trsfiltro;

    String filtro;

    private TableRowSorter trsgrados;
    String grados;

    public datospersonales() {
        initComponents();
        consultar();
        //centrar letras
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        tabla1.setDefaultRenderer(Object.class, centerRenderer);

        // llamar la clase estadocellrender
        ColumnaAmarillaRenderer columnaAmarillaRenderer = new ColumnaAmarillaRenderer(0);
        tabla1.getColumnModel().getColumn(0).setCellRenderer(columnaAmarillaRenderer);
        mostrarfechadecolombia();
        
           AnimacionBorderPanel1 animatedBorderPanel1 = new AnimacionBorderPanel1(jPanel2, jLabel2);
              AnimacionBorderPanel1 animatedBorderPanel2 = new AnimacionBorderPanel1(jPanel5, jLabel2);
              AnimacionBorderPanel1 animatedBorderPanel3 = new AnimacionBorderPanel1(jPanel8, jLabel2);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        NOMBRE = new javax.swing.JLabel();
        txtANombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtApe = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtacudiente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtcorreo = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtfecha = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtidentidad = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtcelular = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtgrado = new javax.swing.JTextField();
        hora = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnAgregar2 = new javax.swing.JButton();
        btnmodificar2 = new javax.swing.JButton();
        btneliminar2 = new javax.swing.JButton();
        btnNuevo2 = new javax.swing.JButton();
        jButton1buscarnombre2 = new javax.swing.JButton();
        txtbuscar2 = new javax.swing.JTextField();
        jButton2buscargrado2 = new javax.swing.JButton();
        txtgrados2 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        pdftabla2 = new javax.swing.JButton();
        jButton6archivotxt2 = new javax.swing.JButton();
        btnexportarexcel2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabla1 = new javax.swing.JTable();

        jPanel2.setBackground(new java.awt.Color(51, 0, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INGRESES SUS DATOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Courier New", 1, 14), new java.awt.Color(0, 255, 255))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID automatico");

        txtid.setEditable(false);
        txtid.setEnabled(false);
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });

        NOMBRE.setBackground(new java.awt.Color(255, 255, 255));
        NOMBRE.setForeground(new java.awt.Color(0, 255, 255));
        NOMBRE.setText("NOMBRE");

        txtANombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtANombreKeyTyped(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setForeground(new java.awt.Color(0, 255, 255));
        jLabel4.setText("APELLIDO");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setForeground(new java.awt.Color(0, 255, 255));
        jLabel5.setText("EDAD");

        jLabel6.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 255, 255));
        jLabel6.setText("DATOS PERSONALES");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setText("ACUDIENTE");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setForeground(new java.awt.Color(0, 255, 255));
        jLabel8.setText("Correo");

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setForeground(new java.awt.Color(0, 255, 255));
        jLabel15.setText("F NACIMIENTO (año/mes/dia)");

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setForeground(new java.awt.Color(0, 255, 255));
        jLabel20.setText("TI O CC");

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setForeground(new java.awt.Color(0, 255, 255));
        jLabel9.setText("N.U CELULAR 1");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(0, 255, 255));
        jLabel3.setText("GRADO ");

        hora.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(hora, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(314, 314, 314))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addGap(12, 12, 12))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(NOMBRE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtApe, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtANombre, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtacudiente, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtgrado, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel20)
                                .addGap(18, 18, 18)
                                .addComponent(txtidentidad, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel15))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtcelular, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6))
                    .addComponent(hora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NOMBRE)
                    .addComponent(txtANombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtacudiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtidentidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtApe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtgrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(txtcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtcelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );

        jPanel5.setBackground(new java.awt.Color(51, 0, 51));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "OPERACIONES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(0, 255, 255))); // NOI18N

        btnAgregar2.setBackground(new java.awt.Color(153, 153, 153));
        btnAgregar2.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        btnAgregar2.setForeground(new java.awt.Color(0, 0, 0));
        btnAgregar2.setText("agregar");
        btnAgregar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar2ActionPerformed(evt);
            }
        });

        btnmodificar2.setBackground(new java.awt.Color(153, 153, 153));
        btnmodificar2.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        btnmodificar2.setForeground(new java.awt.Color(0, 0, 0));
        btnmodificar2.setText("modificar");
        btnmodificar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificar2ActionPerformed(evt);
            }
        });

        btneliminar2.setBackground(new java.awt.Color(153, 153, 153));
        btneliminar2.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        btneliminar2.setForeground(new java.awt.Color(0, 0, 0));
        btneliminar2.setText("eliminar");
        btneliminar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminar2ActionPerformed(evt);
            }
        });

        btnNuevo2.setBackground(new java.awt.Color(153, 153, 153));
        btnNuevo2.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        btnNuevo2.setForeground(new java.awt.Color(0, 0, 0));
        btnNuevo2.setText("nuevo");
        btnNuevo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevo2ActionPerformed(evt);
            }
        });

        jButton1buscarnombre2.setBackground(new java.awt.Color(153, 153, 153));
        jButton1buscarnombre2.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jButton1buscarnombre2.setForeground(new java.awt.Color(0, 0, 0));
        jButton1buscarnombre2.setText("buscar nombre");
        jButton1buscarnombre2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1buscarnombre2ActionPerformed(evt);
            }
        });

        txtbuscar2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbuscar2KeyTyped(evt);
            }
        });

        jButton2buscargrado2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2buscargrado2.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jButton2buscargrado2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2buscargrado2.setText("buscar grados ");
        jButton2buscargrado2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2buscargrado2ActionPerformed(evt);
            }
        });

        txtgrados2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtgrados2KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton1buscarnombre2)
                        .addGap(18, 18, 18)
                        .addComponent(txtbuscar2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2buscargrado2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtgrados2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnAgregar2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnmodificar2)
                        .addGap(18, 18, 18)
                        .addComponent(btneliminar2)
                        .addGap(18, 18, 18)
                        .addComponent(btnNuevo2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnmodificar2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btneliminar2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevo2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1buscarnombre2)
                    .addComponent(txtbuscar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2buscargrado2)
                    .addComponent(txtgrados2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(51, 0, 51));
        jPanel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pdftabla2.setBackground(new java.awt.Color(0, 0, 0));
        pdftabla2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/PDF_24287.png"))); // NOI18N
        pdftabla2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdftabla2ActionPerformed(evt);
            }
        });
        jPanel6.add(pdftabla2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));

        jButton6archivotxt2.setBackground(new java.awt.Color(0, 0, 0));
        jButton6archivotxt2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/txt_text_file_format_extension_icon_124600.png"))); // NOI18N
        jButton6archivotxt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6archivotxt2ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton6archivotxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        btnexportarexcel2.setBackground(new java.awt.Color(0, 0, 0));
        btnexportarexcel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Excel_2013_23480.png"))); // NOI18N
        btnexportarexcel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexportarexcel2ActionPerformed(evt);
            }
        });
        jPanel6.add(btnexportarexcel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, -1, -1));

        jLabel11.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("IMPORTAR");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(2192, 3, -1, 83));

        jLabel10.setBackground(new java.awt.Color(51, 0, 51));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/200.gif"))); // NOI18N
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 350, 180));

        jPanel8.setBackground(new java.awt.Color(51, 0, 51));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BASE DE DATOS PERSONALES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Courier New", 1, 14), new java.awt.Color(0, 255, 255))); // NOI18N

        tabla1.setBackground(new java.awt.Color(51, 0, 51));
        tabla1.setForeground(new java.awt.Color(255, 255, 255));
        tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "nombre", "apellido", "edad", "acudiente", "grado", "correo", "dni", "f nacimiento", "celular"
            }
        ));
        tabla1.setRowHeight(24);
        tabla1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla1MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tabla1);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void txtANombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtANombreKeyTyped

    }//GEN-LAST:event_txtANombreKeyTyped

    private void btnAgregar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar2ActionPerformed
        Agregar();
        consultar();
    }//GEN-LAST:event_btnAgregar2ActionPerformed

    private void btnmodificar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificar2ActionPerformed
        Modificar();
        consultar();
        Nuevo();
    }

    void Modificar() {
        String nom = txtANombre.getText();
        String ape = txtApe.getText();
        String edad = txtEdad.getText();
        String acu = txtacudiente.getText();
        String grado = txtgrado.getText();
        String correo = txtcorreo.getText();
        String identidad = txtidentidad.getText();
        String fecha = txtfecha.getText();
        String celular = txtcelular.getText();
        try {
            if (nom.equals("") || ape.equals("") || edad.equals("") || acu.equals("") || grado.equals("") || correo.equals("") || identidad.equals("") || fecha.equals("") || celular.equals("")) {
                JOptionPane.showMessageDialog(null, "Faltan ingresar datos");
                limipiarTabla();
            } else {
                String sql = "Update alumno set id='" + idc + "',nombre='" + nom + "',apellido="
                        + "'" + ape + "',edad='" + edad + "'"
                        + ",acudiente='" + acu + "',grado='" + grado + "',correo='" + correo + "',identidad='" + identidad + "',fecha='" + fecha + "',celular='" + celular + "' where id=" + idc;
                conet = con2.getConnection2();
                st = conet.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Datos del alumno modificados");
                limipiarTabla();
            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_btnmodificar2ActionPerformed

    private void btneliminar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminar2ActionPerformed
        eliminar();
        consultar();
        Nuevo();
    }//GEN-LAST:event_btneliminar2ActionPerformed

    private void btnNuevo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevo2ActionPerformed
        Nuevo();
    }//GEN-LAST:event_btnNuevo2ActionPerformed

    private void jButton1buscarnombre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1buscarnombre2ActionPerformed
        txtbuscar2.addKeyListener(new KeyAdapter() {

            public void keyReleased(final KeyEvent e) {
                String cadena = txtbuscar2.getText();
                txtbuscar2.setText(cadena);
                repaint();
                filtro();
            }
        });
    }//GEN-LAST:event_jButton1buscarnombre2ActionPerformed

    private void txtbuscar2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscar2KeyTyped
        trsfiltro = new TableRowSorter(tabla1.getModel());
        tabla1.setRowSorter(trsfiltro);
    }//GEN-LAST:event_txtbuscar2KeyTyped

    private void jButton2buscargrado2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2buscargrado2ActionPerformed
       txtgrados2.addKeyListener(new KeyAdapter() {

            public void keyReleased(final KeyEvent e) {
                String cadena = txtgrados2.getText();
                txtgrados2.setText(cadena);
                repaint();
                grados();
            }
        });
    }//GEN-LAST:event_jButton2buscargrado2ActionPerformed

    private void txtgrados2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtgrados2KeyTyped
        trsgrados = new TableRowSorter(tabla1.getModel());
        tabla1.setRowSorter(trsgrados);
    }//GEN-LAST:event_txtgrados2KeyTyped

    private void btnexportarexcel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexportarexcel2ActionPerformed
        try {
            obj = new Exportar();
            obj.exportarExcel(tabla1);
        } catch (IOException ex) {
        }
    }//GEN-LAST:event_btnexportarexcel2ActionPerformed

    private void jButton6archivotxt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6archivotxt2ActionPerformed
        String path = "";
        JFileChooser j = new JFileChooser();
        j.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int x = j.showSaveDialog(this);
        if (x == JFileChooser.APPROVE_OPTION) {
            path = j.getSelectedFile().getPath();
        }
        try {
            FileWriter fw = new FileWriter(path + "DATOS PERSONALES.txt");
            BufferedWriter bw = new BufferedWriter(fw);
            for (int i = 0; i < tabla1.getRowCount(); i++) {
                String LN = tabla1.getValueAt(i, 1).toString();
                String MN = tabla1.getValueAt(i, 2).toString();
                String QN = tabla1.getValueAt(i, 3).toString();
                String PN = tabla1.getValueAt(i, 4).toString();
                String KN = tabla1.getValueAt(i, 5).toString();
                String AN = tabla1.getValueAt(i, 6).toString();
                String EN = tabla1.getValueAt(i, 7).toString();
                String WN = tabla1.getValueAt(i, 8).toString();
                String ÑN = tabla1.getValueAt(i, 9).toString();
                bw.write(LN + "\t" + MN + "\t" + QN + "\t" + PN + "\t" + KN + "\t" + AN + "\t" + EN + "\t" + WN + "\t" + ÑN);
                bw.newLine();
            }
            bw.close();
            JOptionPane.showMessageDialog(null, "Archivo TXT generado");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton6archivotxt2ActionPerformed

    private void pdftabla2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdftabla2ActionPerformed

        // en esta linea implemente Significa que estás obteniendo la
        //ruta del directorio seleccionado por el usuario en un cuadro de diálogo
        //de selección de directorio (JFileChooser) y asignándola a una variable llamada variablepdf.
        String variablepdf = "";
        JFileChooser j = new JFileChooser();
        j.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int x = j.showSaveDialog(this);
        if (x == JFileChooser.APPROVE_OPTION) {
            variablepdf = j.getSelectedFile().getPath();
        }
        Document doc = new Document(new Rectangle(1200, 2000));
        try {
            PdfWriter writer = PdfWriter.getInstance(doc, new FileOutputStream(variablepdf + "abelito.pdf"));
            // Implementar la clase PdfPageEventHelper
            writer.setPageEvent(new PdfPageEventHelper() {
                @Override
                public void onEndPage(PdfWriter writer, Document document) {
                    // Rotar la página 360 grados en sentido antihorario
                    writer.addPageDictEntry(PdfName.ROTATE, new PdfNumber(360));
                }
            });
            doc.open();
            PdfPTable tbl = new PdfPTable(9);
            tbl.addCell("nombre");
            tbl.addCell("apellido");
            tbl.addCell("edad");
            tbl.addCell("acudiente");
            tbl.addCell("grado");
            tbl.addCell("correo");
            tbl.addCell("documento");
            tbl.addCell("f nacimiento");
            tbl.addCell("celular");

            for (int i = 0; i < tabla1.getRowCount(); i++) {

                String LN = tabla1.getValueAt(i, 1).toString();
                String MN = tabla1.getValueAt(i, 2).toString();
                String QN = tabla1.getValueAt(i, 3).toString();
                String PN = tabla1.getValueAt(i, 4).toString();
                String KN = tabla1.getValueAt(i, 5).toString();
                String AN = tabla1.getValueAt(i, 6).toString();
                String EN = tabla1.getValueAt(i, 7).toString();
                String WN = tabla1.getValueAt(i, 8).toString();
                String ÑN = tabla1.getValueAt(i, 9).toString();
                tbl.addCell(LN);
                tbl.addCell(MN);
                tbl.addCell(QN);
                tbl.addCell(PN);
                tbl.addCell(KN);
                tbl.addCell(AN);
                tbl.addCell(EN);
                tbl.addCell(WN);
                tbl.addCell(ÑN);
            }
            doc.add(tbl);
            JOptionPane.showMessageDialog(null, "PDF GENERADO");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "no se pudo generar el mensaje");
        } finally {
            if (doc != null) {
                doc.close();
            }
        }
    }//GEN-LAST:event_pdftabla2ActionPerformed

    private void tabla1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla1MouseClicked
        int fila = tabla1.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "no se selecciono fila");
        } else {
            idc = Integer.parseInt((String) tabla1.getValueAt(fila, 0).toString());
            String nom = (String) tabla1.getValueAt(fila, 1);
            String ape = (String) tabla1.getValueAt(fila, 2);
            int edad = Integer.parseInt((String) tabla1.getValueAt(fila, 3).toString());
            String acu = (String) tabla1.getValueAt(fila, 4);
            String grado = (String) tabla1.getValueAt(fila, 5);
            String correo = (String) tabla1.getValueAt(fila, 6);
            String identidad = (String) tabla1.getValueAt(fila, 7);
            String fecha = (String) tabla1.getValueAt(fila, 8);
            String celular = (String) tabla1.getValueAt(fila, 9);

            txtid.setText("" + idc);
            txtANombre.setText(nom);
            txtApe.setText(ape);
            txtEdad.setText("" + edad);
            txtacudiente.setText(acu);
            txtgrado.setText(grado);
            txtcorreo.setText(correo);
            txtidentidad.setText(identidad);
            txtfecha.setText(fecha);
            txtcelular.setText(celular);
        }
    }//GEN-LAST:event_tabla1MouseClicked

    private void mostrarfechadecolombia() {
        ZoneId zonaColombia = ZoneId.of("America/Bogota");
        LocalDate fechaColombia = LocalDate.now(zonaColombia);
        DateTimeFormatter formatoFecha = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        String fechaColombiaFormateada = fechaColombia.format(formatoFecha);
        hora.setText("" + fechaColombiaFormateada);

    }

    public void grados() {
        grados = txtgrados2.getText();
        trsgrados.setRowFilter(RowFilter.regexFilter(txtgrados2.getText(), 5));
    }

    public void filtro() {
        filtro = txtbuscar2.getText();
        trsfiltro.setRowFilter(RowFilter.regexFilter(txtbuscar2.getText(), 1));
    }

    void consultar() {
        String sql = "select * from alumno ";
        try {
            conet = con2.getConnection2();
            st = conet.createStatement();
            rs = st.executeQuery(sql);
            Object[] alumno = new Object[10];
            modelo = (DefaultTableModel) tabla1.getModel();
            while (rs.next()) {
                alumno[0] = rs.getInt("id");
                alumno[1] = rs.getString("nombre");
                alumno[2] = rs.getString("apellido");
                alumno[3] = rs.getInt("edad");
                alumno[4] = rs.getString("acudiente");
                alumno[5] = rs.getString("grado");
                alumno[6] = rs.getString("correo");
                alumno[7] = rs.getString("identidad");
                alumno[8] = rs.getString("fecha");
                alumno[9] = rs.getString("celular");

                modelo.addRow(alumno);
            }
            tabla1.setModel(modelo);

        } catch (Exception e) {
        }
    }

    void Agregar() {
        String nom = txtANombre.getText();
        String ape = txtApe.getText();
        String edad = txtEdad.getText();
        String acu = txtacudiente.getText();
        String grado = txtgrado.getText();
        String correo = txtcorreo.getText();
        String identidad = txtidentidad.getText();
        String fecha = txtfecha.getText();
        String celular = txtcelular.getText();
        try {
            if (nom.equals("") || ape.equals("") || edad.equals("") || acu.equals("") || grado.equals("") || correo.equals("") || identidad.equals("") || fecha.equals("") || celular.equals("")) {
                JOptionPane.showMessageDialog(null, "Faltan ingresar datos");
                limipiarTabla();
            } else {
                String sql = "insert into alumno(nombre, apellido, edad, acudiente, grado, correo, identidad, fecha, celular) values ('" + nom + "','" + ape + "','" + edad + "','" + acu + "','" + grado + "','" + correo + "','" + identidad + "','" + fecha + "','" + celular + "')";
                conet = con2.getConnection2();
                st = conet.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "nuevo alumno registrado");
                limipiarTabla();
            }
        } catch (Exception e) {
        }
    }

    void limipiarTabla() {
        for (int i = 0; i <= tabla1.getRowCount(); i++) {
            modelo.removeRow(i);
            i = i - 1;
        }

    }

    void eliminar() {
        int fila = tabla1.getSelectedRow();
        try {
            if (fila < 0) {
                JOptionPane.showMessageDialog(null, "alumno no seleccionado");

                limipiarTabla();
            } else {
                String sql = "delete from alumno where id=" + idc;
                conet = con2.getConnection2();
                st = conet.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "alumno eliminado");

                limipiarTabla();

            }
        } catch (Exception e) {

        }
    }

    void Nuevo() {
        txtid.setText("");
        txtANombre.setText("");
        txtApe.setText("");
        txtEdad.setText("");
        txtid.requestFocus();
        txtacudiente.setText("");
        txtgrado.setText("");
        txtcorreo.setText("");
        txtidentidad.setText("");
        txtfecha.setText("");
        txtcelular.setText("");

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NOMBRE;
    private javax.swing.JButton btnAgregar2;
    private javax.swing.JButton btnNuevo2;
    private javax.swing.JButton btneliminar2;
    private javax.swing.JButton btnexportarexcel2;
    private javax.swing.JButton btnmodificar2;
    private javax.swing.JLabel hora;
    private javax.swing.JButton jButton1buscarnombre2;
    private javax.swing.JButton jButton2buscargrado2;
    private javax.swing.JButton jButton6archivotxt2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton pdftabla2;
    private javax.swing.JTable tabla1;
    private javax.swing.JTextField txtANombre;
    private javax.swing.JTextField txtApe;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtacudiente;
    private javax.swing.JTextField txtbuscar2;
    private javax.swing.JTextField txtcelular;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtfecha;
    private javax.swing.JTextField txtgrado;
    private javax.swing.JTextField txtgrados2;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtidentidad;
    // End of variables declaration//GEN-END:variables
}
