/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pantalla;

import Conexion.Conexion;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import renderizador.ColumnaAmarillaRenderer;

/**
 *
 * @author abel
 */
public class datosacademicos extends javax.swing.JPanel {

    Conexion con2 = new Conexion();
    Connection conet;
    DefaultTableModel modelo;
    Statement st;
    ResultSet rs;
    int idc;
    private TableRowSorter trsfiltro;

    String filtro;

    private TableRowSorter trsgrados;
    String grados;

    public datosacademicos() {
        initComponents();

        initComponents();

        consultar();

        //centrar letras
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        tabladedatosacademicos.setDefaultRenderer(Object.class, centerRenderer);

        ColumnaAmarillaRenderer columnaAmarillaRenderer = new ColumnaAmarillaRenderer(0);
        tabladedatosacademicos.getColumnModel().getColumn(0).setCellRenderer(columnaAmarillaRenderer);

        mostrarHoraDeColombia();
        mostrarfechadecolombia();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5datosacademicos = new javax.swing.JPanel();
        jLabel13fechadeingreso = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16colegiodeprocedencia = new javax.swing.JLabel();
        jLabel17condicion = new javax.swing.JLabel();
        jLabel18observacion = new javax.swing.JLabel();
        jLabel19grado = new javax.swing.JLabel();
        txtingreso = new javax.swing.JTextField();
        txtprocedencia = new javax.swing.JTextField();
        txtcondicion = new javax.swing.JTextField();
        txtobservacion = new javax.swing.JTextField();
        txtgrado = new javax.swing.JTextField();
        jLabel1nombre = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        jPanel1basededatosacademicos = new javax.swing.JPanel();
        jButton1Buscardocumento = new javax.swing.JButton();
        jTextField3Buscardocumento = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabladedatosacademicos = new javax.swing.JTable();
        txtdocumento = new javax.swing.JTextField();
        jLabel2documento = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        hora = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(940, 522));

        jPanel5datosacademicos.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5datosacademicos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS ACADEMICOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel5datosacademicos.setPreferredSize(new java.awt.Dimension(948, 578));

        jLabel13fechadeingreso.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13fechadeingreso.setText("FECHA DE INGRESO");

        jLabel16colegiodeprocedencia.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16colegiodeprocedencia.setText("COLEGIO DE PROCEDENCIA");

        jLabel17condicion.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17condicion.setText("CONDICION ");

        jLabel18observacion.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18observacion.setText("OBSEVACION ");

        jLabel19grado.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19grado.setText("GRADO A CURSAR ");

        jLabel1nombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1nombre.setText("NOMBRE");

        jPanel1basededatosacademicos.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1basededatosacademicos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton1Buscardocumento.setText("buscar documento");

        btnAgregar.setText("agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnmodificar.setText("modificar");
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });

        btneliminar.setText("eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        btnNuevo.setText("nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "base de datos academicos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        tabladedatosacademicos.setBackground(new java.awt.Color(0, 0, 0));
        tabladedatosacademicos.setForeground(new java.awt.Color(255, 255, 255));
        tabladedatosacademicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "dni", "nombre", "fecha de ingreso", "observacion", "colegio de procedencia", "condicion", "grado a cursar"
            }
        ));
        tabladedatosacademicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabladedatosacademicosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabladedatosacademicos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1basededatosacademicosLayout = new javax.swing.GroupLayout(jPanel1basededatosacademicos);
        jPanel1basededatosacademicos.setLayout(jPanel1basededatosacademicosLayout);
        jPanel1basededatosacademicosLayout.setHorizontalGroup(
            jPanel1basededatosacademicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1basededatosacademicosLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnAgregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnmodificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btneliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNuevo)
                .addGap(51, 51, 51)
                .addComponent(jButton1Buscardocumento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField3Buscardocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1basededatosacademicosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1basededatosacademicosLayout.setVerticalGroup(
            jPanel1basededatosacademicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1basededatosacademicosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1basededatosacademicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1basededatosacademicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAgregar)
                        .addComponent(btnmodificar)
                        .addComponent(btneliminar)
                        .addComponent(btnNuevo))
                    .addGroup(jPanel1basededatosacademicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1Buscardocumento)
                        .addComponent(jTextField3Buscardocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel2documento.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2documento.setText("DOCUMENTO");

        txtid.setEditable(false);
        txtid.setEnabled(false);

        hora.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel5datosacademicosLayout = new javax.swing.GroupLayout(jPanel5datosacademicos);
        jPanel5datosacademicos.setLayout(jPanel5datosacademicosLayout);
        jPanel5datosacademicosLayout.setHorizontalGroup(
            jPanel5datosacademicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1basededatosacademicos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5datosacademicosLayout.createSequentialGroup()
                .addGroup(jPanel5datosacademicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5datosacademicosLayout.createSequentialGroup()
                        .addGroup(jPanel5datosacademicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5datosacademicosLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel14))
                            .addGroup(jPanel5datosacademicosLayout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(jPanel5datosacademicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2documento)
                                    .addComponent(jLabel1nombre))
                                .addGap(55, 55, 55)
                                .addGroup(jPanel5datosacademicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtdocumento, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                                    .addComponent(txtnombre))))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel5datosacademicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel16colegiodeprocedencia)
                            .addComponent(jLabel17condicion, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5datosacademicosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5datosacademicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel18observacion)
                            .addComponent(jLabel13fechadeingreso))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel5datosacademicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtingreso)
                            .addComponent(txtobservacion, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addGroup(jPanel5datosacademicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19grado, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(hora, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5datosacademicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtgrado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                    .addComponent(txtcondicion, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtprocedencia, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(218, Short.MAX_VALUE))
        );
        jPanel5datosacademicosLayout.setVerticalGroup(
            jPanel5datosacademicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5datosacademicosLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel5datosacademicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5datosacademicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtdocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2documento))
                    .addGroup(jPanel5datosacademicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtprocedencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16colegiodeprocedencia)))
                .addGap(18, 71, Short.MAX_VALUE)
                .addGroup(jPanel5datosacademicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcondicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17condicion)
                    .addComponent(jLabel1nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5datosacademicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addGroup(jPanel5datosacademicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel5datosacademicosLayout.createSequentialGroup()
                            .addGroup(jPanel5datosacademicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel13fechadeingreso)
                                .addComponent(txtingreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel5datosacademicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel18observacion)
                                .addComponent(txtobservacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(hora, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel5datosacademicosLayout.createSequentialGroup()
                            .addGroup(jPanel5datosacademicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtgrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel19grado))
                            .addGap(48, 48, 48))))
                .addGap(18, 18, 18)
                .addComponent(jPanel1basededatosacademicos, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(201, 201, 201))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5datosacademicos, javax.swing.GroupLayout.DEFAULT_SIZE, 940, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 24, Short.MAX_VALUE)
                .addComponent(jPanel5datosacademicos, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tabladedatosacademicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabladedatosacademicosMouseClicked
        int fila = tabladedatosacademicos.getSelectedRow();
        if (fila == -1) {

            JOptionPane.showMessageDialog(null, "no se selecciono fila");
        } else {
            idc = (int) tabladedatosacademicos.getValueAt(fila, 0);
            String docum = (String) tabladedatosacademicos.getValueAt(fila, 1);
            String nom = (String) tabladedatosacademicos.getValueAt(fila, 2);
            String ingreso = (String) tabladedatosacademicos.getValueAt(fila, 3);
            String obser = (String) tabladedatosacademicos.getValueAt(fila, 4);
            String proce = (String) tabladedatosacademicos.getValueAt(fila, 5);
            String condic = (String) tabladedatosacademicos.getValueAt(fila, 6);
            String gra = (String) tabladedatosacademicos.getValueAt(fila, 7);

            txtid.setText(String.valueOf(idc));
            txtdocumento.setText(docum);
            txtnombre.setText(nom);
            txtingreso.setText(ingreso);
            txtobservacion.setText(obser);
            txtprocedencia.setText(proce);
            txtcondicion.setText(condic);
            txtgrado.setText(gra);
        }
    }//GEN-LAST:event_tabladedatosacademicosMouseClicked

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        Agregar();
        consultar();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
        Modificar();
        consultar();
        Nuevo();
    }

    void Modificar() {
        String docum = txtdocumento.getText();
        String nom = txtnombre.getText();
        String ingreso = txtingreso.getText();
        String obser = txtobservacion.getText();
        String proce = txtprocedencia.getText();
        String condic = txtcondicion.getText();
        String gra = txtgrado.getText();

        try {
            if (nom.equals("") || ingreso.equals("") || obser.equals("") || docum.equals("") || proce.equals("") || condic.equals("") || gra.equals("")) {
                JOptionPane.showMessageDialog(null, "Faltan ingresar datos");
                limipiarTabla();
            } else {
                String sql = "Update datosacademicos set id='" + idc + "',nombre='" + nom + "',ingreso="
                        + "'" + ingreso + "',observacion='" + obser + "'"
                        + ",documento='" + docum + "',procedencia='" + proce + "',condicion='" + condic + "',grado='" + gra + "'where id=" + idc;
                conet = con2.getConnection2();
                st = conet.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "datos del alumno modificados");
                limipiarTabla();
            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_btnmodificarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        eliminar();
        consultar();
        Nuevo();
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        Nuevo();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void mostrarHoraDeColombia() {

        ZoneId zonaColombia = ZoneId.of("America/Bogota");
        LocalTime horaColombia = LocalTime.now(zonaColombia);
        DateTimeFormatter formatoHora = DateTimeFormatter.ofPattern("HH:mm:ss");
        String horaColombiaFormateada = horaColombia.format(formatoHora);
        hora.setText("HORA " + horaColombiaFormateada);
    }

    private void mostrarfechadecolombia() {
        ZoneId zonaColombia = ZoneId.of("America/Bogota");
        LocalDate fechaColombia = LocalDate.now(zonaColombia);
        DateTimeFormatter formatoFecha = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        String fechaColombiaFormateada = fechaColombia.format(formatoFecha);
        txtingreso.setText("" + fechaColombiaFormateada);

    }

    /**
     * @param args the command line arguments
     */
    void consultar() {
        String sql = "select * from datosacademicos ";
        try {

            conet = con2.getConnection2();

            st = conet.createStatement();
            rs = st.executeQuery(sql);
            Object[] datosacademicos = new Object[8];
            modelo = (DefaultTableModel) tabladedatosacademicos.getModel();
            while (rs.next()) {
                datosacademicos[0] = rs.getInt("id");
                datosacademicos[1] = rs.getString("documento");
                datosacademicos[2] = rs.getString("nombre");
                datosacademicos[3] = rs.getString("ingreso");
                datosacademicos[4] = rs.getString("observacion");;
                datosacademicos[5] = rs.getString("procedencia");
                datosacademicos[6] = rs.getString("condicion");
                datosacademicos[7] = rs.getString("grado");

                modelo.addRow(datosacademicos);

            }
            tabladedatosacademicos.setModel(modelo);

        } catch (Exception e) {
        }
    }

    void Agregar() {
        String nom = txtnombre.getText();
        String docum = txtdocumento.getText();
        String ingreso = txtingreso.getText();
        String obser = txtobservacion.getText();
        String proce = txtprocedencia.getText();
        String condic = txtcondicion.getText();
        String gra = txtgrado.getText();

        try {
            if (docum.equals("") || nom.equals("") || ingreso.equals("") || obser.equals("") || proce.equals("") || condic.equals("") || gra.equals("")) {
                JOptionPane.showMessageDialog(null, "Faltan ingresar datos");
                limipiarTabla();
            } else {
                String sql = "insert into datosacademicos( documento,nombre, ingreso, observacion,  procedencia, condicion, grado) values ('" + docum + "','" + nom + "','" + ingreso + "','" + obser + "','" + proce + "','" + condic + "','" + gra + "' )";
                conet = con2.getConnection2();
                st = conet.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "nuevo alumno registrado");
                limipiarTabla();
            }
        } catch (Exception e) {
        }

    }

    void limipiarTabla() {
        for (int i = 0; i <= tabladedatosacademicos.getRowCount(); i++) {
            modelo.removeRow(i);
            i = i - 1;
        }

    }

    void eliminar() {
        int fila = tabladedatosacademicos.getSelectedRow();
        try {
            if (fila < 0) {
                JOptionPane.showMessageDialog(null, "alumno no seleccionado");

                limipiarTabla();
            } else {
                String sql = "delete from datosacademicos where id=" + idc;
                conet = con2.getConnection2();
                st = conet.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "alumno eliminado");

                limipiarTabla();

            }
        } catch (Exception e) {

        }
    }

    void Nuevo() {
        txtid.setText("");
        txtdocumento.setText("");
        txtnombre.setText("");
        txtingreso.setText("");
        txtobservacion.setText("");
        txtid.requestFocus();
        txtprocedencia.setText("");
        txtcondicion.setText("");
        txtgrado.setText("");

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JLabel hora;
    private javax.swing.JButton jButton1Buscardocumento;
    private javax.swing.JLabel jLabel13fechadeingreso;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16colegiodeprocedencia;
    private javax.swing.JLabel jLabel17condicion;
    private javax.swing.JLabel jLabel18observacion;
    private javax.swing.JLabel jLabel19grado;
    private javax.swing.JLabel jLabel1nombre;
    private javax.swing.JLabel jLabel2documento;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel1basededatosacademicos;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5datosacademicos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3Buscardocumento;
    private javax.swing.JTable tabladedatosacademicos;
    private javax.swing.JTextField txtcondicion;
    private javax.swing.JTextField txtdocumento;
    private javax.swing.JTextField txtgrado;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtingreso;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtobservacion;
    private javax.swing.JTextField txtprocedencia;
    // End of variables declaration//GEN-END:variables
}
