package pantalla;

import Conexion.Conexion;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import renderizador.AnimacionBorderPanel1;
import renderizador.ColumnaAmarillaRenderer;

public class datosacademicos extends javax.swing.JPanel {

    Conexion con2 = new Conexion();
    Connection conet;
    DefaultTableModel modelo;
    Statement st;
    ResultSet rs;
    int idc;
    private TableRowSorter trsfiltro;

    String filtro;

    private TableRowSorter trsgrados;
    String grados;

    public datosacademicos() {
        initComponents();

        consultar();

        //centrar letras
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        tabladedatosacademicos.setDefaultRenderer(Object.class, centerRenderer);

        ColumnaAmarillaRenderer columnaAmarillaRenderer = new ColumnaAmarillaRenderer(0);
        tabladedatosacademicos.getColumnModel().getColumn(0).setCellRenderer(columnaAmarillaRenderer);


        mostrarfechadecolombia();

        AnimacionBorderPanel1 animatedBorderPanel2 = new AnimacionBorderPanel1(jPanel1, jLabel18observacion);
        AnimacionBorderPanel1 animatedBorderPanel3 = new AnimacionBorderPanel1(jPanel2, jLabel1nombre);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtobservacion = new javax.swing.JTextField();
        txtgrado = new javax.swing.JTextField();
        jLabel13fechadeingreso = new javax.swing.JLabel();
        jLabel1nombre = new javax.swing.JLabel();
        txtdocumento = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        jLabel2documento = new javax.swing.JLabel();
        jLabel16colegiodeprocedencia = new javax.swing.JLabel();
        jLabel17condicion = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel18observacion = new javax.swing.JLabel();
        jLabel19grado = new javax.swing.JLabel();
        txtingreso = new javax.swing.JTextField();
        txtprocedencia = new javax.swing.JTextField();
        txtcondicion = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabladedatosacademicos = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("propiedades"));

        jLabel13fechadeingreso.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13fechadeingreso.setText("FECHA DE INGRESO");

        jLabel1nombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1nombre.setText("NOMBRE");

        jLabel2documento.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2documento.setText("DOCUMENTO");

        jLabel16colegiodeprocedencia.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16colegiodeprocedencia.setText("COLEGIO DE PROCEDENCIA");

        jLabel17condicion.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17condicion.setText("CONDICION ");

        txtid.setEditable(false);
        txtid.setEnabled(false);

        jLabel18observacion.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18observacion.setText("OBSEVACION ");

        jLabel19grado.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19grado.setText("GRADO A CURSAR ");

        btnAgregar.setText("agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnmodificar.setText("modificar");
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });

        btneliminar.setText("eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        btnNuevo.setText("nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2documento)
                            .addComponent(jLabel1nombre)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13fechadeingreso))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAgregar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(77, 77, 77))
                            .addComponent(jLabel18observacion, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtingreso, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtobservacion, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtdocumento)
                                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16colegiodeprocedencia)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel19grado)
                                            .addComponent(jLabel17condicion))
                                        .addGap(10, 10, 10)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnmodificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btneliminar)
                        .addGap(18, 18, 18)
                        .addComponent(btnNuevo)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtgrado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                    .addComponent(txtcondicion, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtprocedencia, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtdocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2documento)
                        .addComponent(jLabel16colegiodeprocedencia))
                    .addComponent(txtprocedencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel17condicion)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13fechadeingreso)
                                    .addComponent(txtgrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtcondicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(45, 45, 45)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtingreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19grado))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtobservacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18observacion))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAgregar)
                            .addComponent(btneliminar)
                            .addComponent(btnNuevo)
                            .addComponent(btnmodificar))
                        .addGap(28, 28, 28))))
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel2.setForeground(new java.awt.Color(0, 0, 0));

        tabladedatosacademicos.setBackground(new java.awt.Color(51, 0, 51));
        tabladedatosacademicos.setForeground(new java.awt.Color(255, 255, 255));
        tabladedatosacademicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "dni", "nombre", "fecha de ingreso", "observacion", "colegio de procedencia", "condicion", "grado a cursar"
            }
        ));
        tabladedatosacademicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabladedatosacademicosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabladedatosacademicos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tabladedatosacademicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabladedatosacademicosMouseClicked
        int fila = tabladedatosacademicos.getSelectedRow();
        if (fila == -1) {

            JOptionPane.showMessageDialog(null, "no se selecciono fila");
        } else {
            idc = (int) tabladedatosacademicos.getValueAt(fila, 0);
            String docum = (String) tabladedatosacademicos.getValueAt(fila, 1);
            String nom = (String) tabladedatosacademicos.getValueAt(fila, 2);
            String ingreso = (String) tabladedatosacademicos.getValueAt(fila, 3);
            String obser = (String) tabladedatosacademicos.getValueAt(fila, 4);
            String proce = (String) tabladedatosacademicos.getValueAt(fila, 5);
            String condic = (String) tabladedatosacademicos.getValueAt(fila, 6);
            String gra = (String) tabladedatosacademicos.getValueAt(fila, 7);

            txtid.setText(String.valueOf(idc));
            txtdocumento.setText(docum);
            txtnombre.setText(nom);
            txtingreso.setText(ingreso);
            txtobservacion.setText(obser);
            txtprocedencia.setText(proce);
            txtcondicion.setText(condic);
            txtgrado.setText(gra);
        }
    }//GEN-LAST:event_tabladedatosacademicosMouseClicked

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        Agregar();
        consultar();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
        Modificar();
        consultar();
        Nuevo();
    }

    void Modificar() {
        String docum = txtdocumento.getText();
        String nom = txtnombre.getText();
        String ingreso = txtingreso.getText();
        String obser = txtobservacion.getText();
        String proce = txtprocedencia.getText();
        String condic = txtcondicion.getText();
        String gra = txtgrado.getText();

        try {
            if (nom.equals("") || ingreso.equals("") || obser.equals("") || docum.equals("") || proce.equals("") || condic.equals("") || gra.equals("")) {
                JOptionPane.showMessageDialog(null, "Faltan ingresar datos");
                limipiarTabla();
            } else {
                String sql = "Update datosacademicos set id='" + idc + "',nombre='" + nom + "',ingreso="
                        + "'" + ingreso + "',observacion='" + obser + "'"
                        + ",documento='" + docum + "',procedencia='" + proce + "',condicion='" + condic + "',grado='" + gra + "'where id=" + idc;
                conet = con2.getConnection2();
                st = conet.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "datos del alumno modificados");
                limipiarTabla();
            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_btnmodificarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        eliminar();
        consultar();
        Nuevo();
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        Nuevo();
    }//GEN-LAST:event_btnNuevoActionPerformed


    void mostrarfechadecolombia() {
        ZoneId zonaColombia = ZoneId.of("America/Bogota");
        LocalDate fechaColombia = LocalDate.now(zonaColombia);
        DateTimeFormatter formatoFecha = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        String fechaColombiaFormateada = fechaColombia.format(formatoFecha);
        txtingreso.setText("" + fechaColombiaFormateada);

    }

    void consultar() {
        String sql = "select * from datosacademicos ";
        try {

            conet = con2.getConnection2();

            st = conet.createStatement();
            rs = st.executeQuery(sql);
            Object[] datosacademicos = new Object[8];
            modelo = (DefaultTableModel) tabladedatosacademicos.getModel();
            while (rs.next()) {
                datosacademicos[0] = rs.getInt("id");
                datosacademicos[1] = rs.getString("documento");
                datosacademicos[2] = rs.getString("nombre");
                datosacademicos[3] = rs.getString("ingreso");
                datosacademicos[4] = rs.getString("observacion");;
                datosacademicos[5] = rs.getString("procedencia");
                datosacademicos[6] = rs.getString("condicion");
                datosacademicos[7] = rs.getString("grado");

                modelo.addRow(datosacademicos);

            }
            tabladedatosacademicos.setModel(modelo);

        } catch (Exception e) {
        }
    }

    void Agregar() {
        String nom = txtnombre.getText();
        String docum = txtdocumento.getText();
        String ingreso = txtingreso.getText();
        String obser = txtobservacion.getText();
        String proce = txtprocedencia.getText();
        String condic = txtcondicion.getText();
        String gra = txtgrado.getText();

        try {
            if (docum.equals("") || nom.equals("") || ingreso.equals("") || obser.equals("") || proce.equals("") || condic.equals("") || gra.equals("")) {
                JOptionPane.showMessageDialog(null, "Faltan ingresar datos");
                limipiarTabla();
            } else {
                String sql = "insert into datosacademicos( documento,nombre, ingreso, observacion,  procedencia, condicion, grado) values ('" + docum + "','" + nom + "','" + ingreso + "','" + obser + "','" + proce + "','" + condic + "','" + gra + "' )";
                conet = con2.getConnection2();
                st = conet.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "nuevo alumno registrado");
                limipiarTabla();
            }
        } catch (Exception e) {
        }

    }

    void limipiarTabla() {
        for (int i = 0; i <= tabladedatosacademicos.getRowCount(); i++) {
            modelo.removeRow(i);
            i = i - 1;
        }

    }

    void eliminar() {
        int fila = tabladedatosacademicos.getSelectedRow();
        try {
            if (fila < 0) {
                JOptionPane.showMessageDialog(null, "alumno no seleccionado");

                limipiarTabla();
            } else {
                String sql = "delete from datosacademicos where id=" + idc;
                conet = con2.getConnection2();
                st = conet.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "alumno eliminado");

                limipiarTabla();

            }
        } catch (Exception e) {

        }
    }

    void Nuevo() {
        txtid.setText("");
        txtdocumento.setText("");
        txtnombre.setText("");
        txtingreso.setText("");
        txtobservacion.setText("");
        txtid.requestFocus();
        txtprocedencia.setText("");
        txtcondicion.setText("");
        txtgrado.setText("");

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13fechadeingreso;
    private javax.swing.JLabel jLabel16colegiodeprocedencia;
    private javax.swing.JLabel jLabel17condicion;
    private javax.swing.JLabel jLabel18observacion;
    private javax.swing.JLabel jLabel19grado;
    private javax.swing.JLabel jLabel1nombre;
    private javax.swing.JLabel jLabel2documento;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabladedatosacademicos;
    private javax.swing.JTextField txtcondicion;
    private javax.swing.JTextField txtdocumento;
    private javax.swing.JTextField txtgrado;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtingreso;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtobservacion;
    private javax.swing.JTextField txtprocedencia;
    // End of variables declaration//GEN-END:variables
}
